version: 2.1

jobs:
  machine_dlc:
    machine:
      docker_layer_caching: true
    steps:
    - run: which docker
    - run: docker -v
    - run:
        name: Build a really docker image
        command: |
          dockerfile=Dockerfile
          echo "FROM ubuntu:22.04" > $dockerfile
          echo "RUN echo hello" >> $dockerfile
          echo "RUN apt-get update && apt-get install -y autoconf build-essential ca-certificates cmake curl file gettext-base gnupg gzip jq libcurl4-openssl-dev libmagic-dev libmariadb-dev libpq-dev" >> $dockerfile
          docker build -f $dockerfile --tag throwaway:$CIRCLE_BUILD_NUM .
          docker run --rm throwaway:$CIRCLE_BUILD_NUM
    - run: mkdir -p docker-images/docker/
    - run: docker save -o docker-images/docker/throwaway-$CIRCLE_BUILD_NUM throwaway:$CIRCLE_BUILD_NUM 
    - run: docker version
    - run:
        name: Retrive logs
        command: journalctl --no-pager
        when: always

    
workflows:
  version: 2
  vm_jobs:
    jobs:
      - machine_dlc
